ALTER TABLE users
  ADD COLUMN user_type VARCHAR(20) NOT NULL DEFAULT 'REGISTERED',
  ADD COLUMN guest_action_count INT NOT NULL DEFAULT 0,
  ADD COLUMN guest_action_limit INT NOT NULL DEFAULT 10,
  ADD COLUMN guest_expires_at DATETIME NULL;
